//TODO: Split in separate files
module.exports.SELECT_CARD = 'SELECT_CARD';
module.exports.ADD_CARD = 'ADD_CARD';
module.exports.REMOVE_CARD = 'REMOVE_CARD';
module.exports.REMOVE_PROC_CARD = 'REMOVE_PROC_CARD';
module.exports.REMOVE_ALL_CARDS = 'REMOVE_ALL_CARDS';
module.exports.MOVE_CARD = 'MOVE_CARD';


module.exports.ADD_CONNECTION = 'ADD_CONNECTION';
module.exports.REMOVE_CONNECTION = 'REMOVE_CONNECTION';
module.exports.REMOVE_ALL_CONNECTIONS = 'REMOVE_ALL_CONNECTIONS';
module.exports.HIGHLIGHT_CONNECTION = 'HIGHLIGHT_CONNECTION';
module.exports.UNHIGHLIGHT_CONNECTION = 'UNHIGHLIGHT_CONNECTION';
module.exports.HIGHLIGHT_ALL_CONNECTIONS = 'HIGHLIGHT_ALL_CONNECTIONS';
module.exports.UNHIGHLIGHT_ALL_CONNECTIONS = 'UNHIGHLIGHT_ALL_CONNECTIONS';

module.exports.ADD_TABLE = 'ADD_TABLE';
module.exports.ADD_SCHEMA = 'ADD_SCHEMA';
module.exports.CHANGE_SCHEMA = 'CHANGE_SCHEMA';

module.exports.UPDATE_STATE = 'UPDATE_STATE';

module.exports.OPEN_RIGHT_SIDEBAR = 'OPEN_RIGHT_SIDEBAR';
module.exports.CLOSE_RIGHT_SIDEBAR = 'CLOSE_RIGHT_SIDEBAR';
module.exports.OPEN_TAB_LEFT_SIDEBAR = 'OPEN_TAB_LEFT_SIDEBAR';

module.exports.OPEN_LEFT_SIDEBAR = 'OPEN_LEFT_SIDEBAR';
module.exports.CLOSE_LEFT_SIDEBAR = 'CLOSE_LEFT_SIDEBAR';
module.exports.OPEN_TAB_RIGHT_SIDEBAR = 'OPEN_TAB_RIGHT_SIDEBAR';


module.exports.OPEN_BLUEPRINT_SIDEBAR = 'OPEN_BLUEPRINT_SIDEBAR';
module.exports.CLOSE_BLUEPRINT_SIDEBAR = 'CLOSE_BLUEPRINT_SIDEBAR';
module.exports.TOGGLE_BLUEPRINT_SIDEBAR = 'TOGGLE_BLUEPRINT_SIDEBAR';


module.exports.ADD_FILTER = 'ADD_FILTER';
module.exports.UPDATE_FILTER = 'UPDATE_FILTER';
module.exports.REMOVE_FILTER = 'REMOVE_FILTER';

module.exports.SHOW_VIZ = 'SHOW_VIZ';
module.exports.HIDE_VIZ = 'HIDE_VIZ';
module.exports.CARD_CONFIGURED = 'CARD_CONFIGURED';

module.exports.UPDATE_FLOW = 'UPDATE_FLOW';

module.exports.MOD_OPTION = 'MOD_OPTION';

module.exports.MOVE_CARD = 'MOVE_CARD';

module.exports.JOIN_DATA = 'JOIN_DATA';

module.exports.SHOW_VIZ_PANEL = 'SHOW_VIZ_PANEL';
module.exports.HIDE_VIZ_PANEL = 'HIDE_VIZ_PANEL';
module.exports.MOD_LAYOUT = 'MOD_LAYOUT';
module.exports.SELECT_NAVBAR_INDEX = 'SELECT_NAVBAR_INDEX';

module.exports.START_CARD_DRAGGING = 'START_CARD_DRAGGING';
module.exports.STOP_CARD_DRAGGING = 'STOP_CARD_DRAGGING';
module.exports.TOGGLE_LEFT_SIDEBAR = 'TOGGLE_LEFT_SIDEBAR';
module.exports.TOGGLE_RIGHT_SIDEBAR = 'TOGGLE_RIGHT_SIDEBAR';

module.exports.SCALE = 'SCALE';
module.exports.TRANSLATE = 'TRANSLATE';

module.exports.SHARE_SELECTED_DATA = 'SHARE_SELECTED_DATA';
module.exports.SHARE_SELECTION = 'SHARE_SELECTION';

module.exports.SHOW_PROGRESS = 'SHOW_PROGRESS';

module.exports.MOD_SELECTION = 'MOD_SELECTION';
module.exports.RM_SELECTION = 'RM_SELECTION';

module.exports.OPEN_CONNECTION = 'OPEN_CONNECTION';

module.exports.SAVE_SESSION = 'SAVE_SESSION';
module.exports.LOAD_SESSION = 'LOAD_SESSION';

module.exports.UPDATE_FILE_LIST = 'UPDATE_FILE_LIST';

module.exports.DI_SELECT_FILE = 'DI_SELECT_FILE';
module.exports.DI_SELECT_SCHEMA = 'DI_SELECT_SCHEMA';

module.exports.SHOW_FILE_LIST = 'SHOW_FILE_LIST';
module.exports.HIDE_FILE_LIST = 'HIDE_FILE_LIST';
module.exports.LIST_FILES = 'LIST_FILES';

module.exports.REMOVE_FILE = 'REMOVE_FILE';

module.exports.RUN_PYSCRIPT = 'RUN_PYSCRIPT';
module.exports.RUN_RSCRIPT = 'RUN_RSCRIPT';

module.exports.ADD_GROUP = 'ADD_GROUP';
module.exports.REMOVE_GROUP = 'REMOVE_GROUP';
module.exports.TOGGLE_GROUP_TITLE = 'TOGGLE_GROUP_TITLE';
module.exports.TOGGLE_GROUP_COLOR = 'TOGGLE_GROUP_COLOR';
module.exports.MOD_GROUP_TITLE = 'MOD_GROUP_TITLE';

module.exports.GROUP_ADD_FILTER = 'GROUP_ADD_FILTER';
module.exports.GROUP_UPDATE_FILTER = 'GROUP_UPDATE_FILTER';
module.exports.GROUP_REMOVE_FILTER = 'GROUP_REMOVE_FILTER';
module.exports.MOD_GROUP_COLOR = 'MOD_GROUP_COLOR';
module.exports.UPDATE_VIZ_LIST = 'UPDATE_VIZ_LIST';

module.exports.SHOW_VIZ_LIST = 'SHOW_VIZ_LIST';
module.exports.HIDE_VIZ_LIST = 'HIDE_VIZ_LIST';
module.exports.REMOVE_VIZ = 'REMOVE_VIZ';
module.exports.REMOVE_CARD = 'REMOVE_CARD';
module.exports.VIZ_DOWNLOAD_ALL = 'VIZ_DOWNLOAD_ALL';
module.exports.VIZ_DOWNLOAD_ONE = 'VIZ_DOWNLOAD_ONE';

module.exports.CARDS_DOWNLOAD_ALL = 'CARDS_DOWNLOAD_ALL';
module.exports.CARDS_DOWNLOAD_ONE = 'CARDS_DOWNLOAD_ONE';

module.exports.UPDATE_USERNAME = 'UPDATE_USERNAME';
module.exports.SHOW_GRAMMAR_EDITOR = 'SHOW_GRAMMAR_EDITOR';
module.exports.HIDE_GRAMMAR_EDITOR = 'HIDE_GRAMMAR_EDITOR';
module.exports.SAVE_GRAMMAR = 'SAVE_GRAMMAR';


module.exports.HIDE_FILE_UPLOAD = 'HIDE_FILE_UPLOAD';
module.exports.SHOW_FILE_UPLOAD = 'SHOW_FILE_UPLOAD';

module.exports.UPDATE_LIB_LIST = 'UPDATE_LIB_LIST';
module.exports.UPDATE_PREVIEW_LIST = 'UPDATE_PREVIEW_LIST';


module.exports.SHOW_VIZ_CREATOR = 'SHOW_VIZ_CREATOR';
module.exports.CLEAR_CREATOR = 'CLEAR_CREATOR';
module.exports.HIDE_VIZ_CREATOR = 'HIDE_VIZ_CREATOR';
module.exports.STEP_VIZ_CREATOR = 'STEP_VIZ_CREATOR';
module.exports.UPDATE_FIELD_VIZ = 'UPDATE_FIELD_VIZ';

module.exports.VIZCREATOR_ADD_CONN = 'VIZCREATOR_ADD_CONN';
module.exports.VIZCREATOR_MOD_CONN = 'VIZCREATOR_MOD_CONN';
module.exports.VIZCREATOR_RM_CONN = 'VIZCREATOR_RM_CONN';

module.exports.MOD_METHOD_ARGS = 'MOD_METHOD_ARGS';
module.exports.MOD_METHOD_CODE = 'MOD_METHOD_CODE';

module.exports.ADD_CARD_OPTION = 'ADD_CARD_OPTION';
module.exports.RM_CARD_OPTION = 'RM_CARD_OPTION';
module.exports.MOD_CARD_OPTION = 'MOD_CARD_OPTION';

module.exports.SEND_CUSTOM_VIZ = 'SEND_CUSTOM_VIZ';
module.exports.EDIT_CUSTOMVIZ = 'EDIT_CUSTOMVIZ';

module.exports.EDIT_FILE_OPTION = 'EDIT_FILE_OPTION';

module.exports.SELECT_PREVIEW_FILE = 'SELECT_PREVIEW_FILE';
module.exports.MOD_STEP_CONFIG = 'MOD_STEP_CONFIG';

module.exports.MOD_VIZ_PREVIEW_OPTION = 'MOD_VIZ_PREVIEW_OPTION';

module.exports.SET_CARD_PROP = 'SET_CARD_PROP';

module.exports.HIDE_FULL_LOADING = 'HIDE_FULL_LOADING';
module.exports.SET_FULL_LOADING_MESSAGE = 'SET_FULL_LOADING_MESSAGE';

module.exports.FINISHED_WORK = 'FINISHED_WORK';
module.exports.START_WORK = 'START_WORK';
module.exports.WORK_CANCELED = 'WORK_CANCELED';
module.exports.PROPAGATE_PROP = 'PROPAGATE_PROP';

module.exports.SET_CARD_OPTIONS = 'SET_CARD_OPTIONS';
module.exports.START_R_SCRIPT = 'START_R_SCRIPT';

module.exports.SET_LEFT_SIDEBAR_STATE = 'SET_LEFT_SIDEBAR_STATE';

module.exports.HIDE_CARD_SELECTOR = 'HIDE_CARD_SELECTOR';
module.exports.SHOW_CARD_SELECTOR = 'SHOW_CARD_SELECTOR';

module.exports.SET_CARD_PROP_VIZPANEL = 'SET_CARD_PROP_VIZPANEL';

module.exports.ADD_PANEL = 'ADD_PANEL';
module.exports.ADD_GRAMMAR_PANEL = 'ADD_GRAMMAR_PANEL';
module.exports.REMOVE_PANEL = 'REMOVE_PANEL';
module.exports.ADD_VIZ_TO_PANEL = 'ADD_VIZ_TO_PANEL';
module.exports.REMOVE_VIZ_FROM_PANEL = 'REMOVE_VIZ_FROM_PANEL';
module.exports.TOGGLE_PANEL_SIDEBAR = 'TOGGLE_PANEL_SIDEBAR';

module.exports.SESSION_INIT = 'SESSION_INIT';
module.exports.SESSION_ADD = 'SESSION_ADD';
module.exports.SESSION_REMOVE = 'SESSION_REMOVE';
module.exports.SESSION_LIST_RELOAD = 'SESSION_LIST_RELOAD';

module.exports.SET_CURRENT_SESSION_ID = 'SET_CURRENT_SESSION_ID';
module.exports.SESSION_LOAD = 'SESSION_LOAD';
module.exports.SESSION_UNLOAD = 'SESSION_UNLOAD';

module.exports.ADD_HIDDEN_CONNECTION = 'ADD_HIDDEN_CONNECTION';
module.exports.REMOVE_HIDDEN_CONNECTION = 'REMOVE_HIDDEN_CONNECTION';
module.exports.ALPHA_HIDDEN_CONNECTION = 'ALPHA_HIDDEN_CONNECTION';

module.exports.ADD_LAYER = 'ADD_LAYER';
module.exports.REMOVE_LAYER = 'REMOVE_LAYER';
module.exports.SET_LAYER_PROP = 'SET_LAYER_PROP';
module.exports.ACTIVATE_LAYER = 'ACTIVATE_LAYER';
module.exports.TOGGLE_LAYER_BRUSH = 'TOGGLE_LAYER_BRUSH';
module.exports.REMOVE_ALL_LAYERS = 'REMOVE_ALL_LAYERS';
module.exports.ADD_GRAMMAR_LAYER = 'ADD_GRAMMAR_LAYER';

module.exports.ADD_CARD_TO_ACTIVE_LAYER = 'ADD_CARD_TO_ACTIVE_LAYER';

module.exports.SET_HOME_SECTION = 'SET_HOME_SECTION';

module.exports.SESSION_DOWNLOAD = 'SESSION_DOWNLOAD';


module.exports.SHOW_MESSAGE = 'SHOW_MESSAGE';
module.exports.HIDE_MESSAGE = 'HIDE_MESSAGE';
module.exports.REMOVE_ALL_FILES = 'REMOVE_ALL_FILES';

module.exports.DOWNLOAD_FILE = 'DOWNLOAD_FILE';

module.exports.RENAME_FILE = 'RENAME_FILE';

module.exports.RENAME_PREVIEW = 'RENAME_PREVIEW';
module.exports.REMOVE_ALL_PREVIEWS = 'REMOVE_ALL_PREVIEWS';
module.exports.REMOVE_PREVIEW = 'REMOVE_PREVIEW';

module.exports.REMOVE_ALL_DEPENDENCIES = 'REMOVE_ALL_DEPENDENCIES';
module.exports.REMOVE_DEPENDENCY = 'REMOVE_DEPENDENCY';

module.exports.VIZ_UPDATE = 'VIZ_UPDATE';

module.exports.SHOW_WORKING_MESSAGE = 'SHOW_WORKING_MESSAGE';
module.exports.HIDE_WORKING_MESSAGE = 'HIDE_WORKING_MESSAGE';


module.exports.SHOW_ERROR_MESSAGE = 'SHOW_ERROR_MESSAGE';
module.exports.HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';


module.exports.SHOW_CONN_CREATOR = 'SHOW_CONN_CREATOR';
module.exports.HIDE_CONN_CREATOR = 'HIDE_CONN_CREATOR';

module.exports.EDIT_CONN = 'EDIT_CONN';
module.exports.UPDATE_FIELD_CONN = 'UPDATE_FIELD_CONN';
module.exports.STRUCTURE_ADD_CHILD = 'STRUCTURE_ADD_CHILD';
module.exports.STRUCTURE_REMOVE_ELEM = 'STRUCTURE_REMOVE_ELEM';

module.exports.STRUCTURE_CHANGE_NODE = 'STRUCTURE_CHANGE_NODE';

module.exports.CLEAR_CONN_CREATOR = 'CLEAR_CONN_CREATOR';
module.exports.SEND_CUSTOM_CONN = 'SEND_CUSTOM_CONN';
module.exports.REMOVE_CUSTOM_CONN = 'REMOVE_CUSTOM_CONN';

module.exports.RESIZE_UI = 'RESIZE_UI';

module.exports.OPTION_SHOW_LB = 'OPTION_SHOW_LB';
module.exports.OPTION_HIDE_LB = 'OPTION_HIDE_LB';

module.exports.CONNECTION_DOWNLOAD = 'CONNECTION_DOWNLOAD';
module.exports.CONNECTION_EDIT = 'CONNECTION_EDIT';

module.exports.REMOVE_ALL_PANELS = 'REMOVE_ALL_PANELS';
module.exports.RESET_UI = 'RESET_UI';


module.exports.SHOW_FLOATING_MENU = 'SHOW_FLOATING_MENU';
module.exports.HIDE_FLOATING_MENU = 'HIDE_FLOATING_MENU';

module.exports.SET_FLOATING_MENU_INDEX = 'SET_FLOATING_MENU_INDEX';
