module.exports.SHOW_VIZ_CREATOR = 'CARD_SHOW_VIZ_CREATOR';
module.exports.HIDE_VIZ_CREATOR = 'CARD_HIDE_VIZ_CREATOR';
module.exports.STEP_VIZ_CREATOR = 'CARD_STEP_VIZ_CREATOR';
module.exports.UPDATE_FIELD_VIZ = 'CARD_UPDATE_FIELD_VIZ';

module.exports.VIZCREATOR_ADD_CONN = 'CARD_VIZCREATOR_ADD_CONN';
module.exports.VIZCREATOR_MOD_CONN = 'CARD_VIZCREATOR_MOD_CONN';
module.exports.VIZCREATOR_RM_CONN = 'CARD_VIZCREATOR_RM_CONN';

module.exports.RM_METHOD_ARGS = 'CARD_RM_METHOD_ARGS';
module.exports.ADD_METHOD_ARGS = 'CARD_ADD_METHOD_ARGS';
module.exports.MOD_METHOD_CODE = 'CARD_MOD_METHOD_CODE';

module.exports.ADD_CARD_OPTION = 'CARD_ADD_CARD_OPTION';
module.exports.RM_CARD_OPTION = 'CARD_RM_CARD_OPTION';
module.exports.MOD_CARD_OPTION = 'CARD_MOD_CARD_OPTION';

module.exports.SEND_CUSTOM_VIZ = 'CARD_SEND_CUSTOM_VIZ';
module.exports.EDIT_CUSTOMVIZ = 'CARD_EDIT_CUSTOMVIZ';

module.exports.EDIT_FILE_OPTION = 'CARD_EDIT_FILE_OPTION';

module.exports.SELECT_PREVIEW_FILE = 'CARD_SELECT_PREVIEW_FILE';
module.exports.MOD_STEP_CONFIG = 'CARD_MOD_STEP_CONFIG';

module.exports.MOD_VIZ_PREVIEW_OPTION = 'CARD_MOD_VIZ_PREVIEW_OPTION';

module.exports.SET_CARD_PROP = 'CARD_SET_CARD_PROP';

module.exports.ADD_METHOD = 'CARD_ADD_METHOD';
module.exports.REMOVE_METHOD = 'CARD_REMOVE_METHOD';
module.exports.RENAME_METHOD = 'CARD_RENAME_METHOD';
module.exports.CLEAR_CREATOR = 'CLEAR_CREATOR';